version: "3"
services:
  hoard:
    image: quay.io/monax/hoard:1.1.3
    network_mode: "host"
  postgres:
    image: postgres:9-alpine
    network_mode: "host"
    environment:
      POSTGRES_USER: blackstone_development
      POSTGRES_PASSWORD: blackstone_development
      POSTGRES_DB: blackstone_development
    ports:
    - "5432:5432"
  chain:
    image: quay.io/monax/build:latest
    network_mode: "host"
    environment:
      CI_PROJECT_DIR: /app
      HOARD_IP: hoard:53431
      NODE_ENV: testing
      MONAX_ECOSYSTEM: MONAX_PLATFORM
    volumes:
    - .:/app
    ports:
    - "3080:3080"
    - "9222:9222"
    - "10997:10997"
    working_dir: /app
    depends_on:
    - postgres
    - hoard
    command: "test/test_api.sh --runAPI"
  vent:
    image: quay.io/monax/vent:develop
    network_mode: "host"
    environment:
      USER: blackstone_development
      PASS: blackstone_development
      POSTGRES_ADDRESS: localhost:5432/blackstone_development?sslmode=disable
      SCHEMA: vent
      BURROW_ADDRESS: localhost:10997
      LOGGING: debug
    volumes:
    - ./api/sqlsol:/config
    depends_on:
    - postgres
    - chain
