version: 2.1
jobs:
  test:
    machine: &machine_defaults
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - &add_ssh_key
        add_ssh_keys:
          fingerprints:
            - "5e:f3:47:75:34:c7:83:93:51:48:31:6a:3a:1a:de:85"
      - checkout
      - run: make docker_test
      - store_artifacts:
          path: ./test/docker-compose.log

workflows:
  test_and_deploy:
    jobs:
      - test
